# Generated by Django 5.1.6 on 2025-05-01 06:03

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed is 50KB', null=True, upload_to='articles/images/%Y/%m/', validators=[news.models.validate_image_size]),
        ),
    ]
